### ISSUE TITLE
Wolverine 3.0 Documentation Punchlist

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#1074]
## Tasks

- [ ] Touch up the quick start. Show cascading actions, use error handling, use Load & new `[Required]` attribute
- [x] In the "Wolverine as Mediator" page, make it clearer that the MediatorOnly setting turns off all async messaging
- [x] In the "Wolverine as Mediator" page, recommend Wolverine.Http instead
- [x] In the "Wolverine as Mediator" page, show the route helpers in Wolverine.Http to delegate to Wolverine. Or at least link to it
- [x] Review the "Best Practices" document. Flesh out "Keep Your Call Stacks Short"
- [x] In "Best Practices", mention that Wolverine is better at graceful shutdown of nodes in 3.0
- [ ] Revisit custom middleware tutorial after the new attribute work. Go over regardless
- [x] Bump message about serverless in that tutorial. Spring 2024 should become "some day"
- [x] Add a discussion of nodes and agents to the "Basic Concepts" page
- [x] Add inbox/outbox to the "Basic Concepts" page
- [x] In "Configuration", link to Wolverine.HTTP configuration
- [x] In "Runtime Architecture", add a new section for nodes & agents. Discuss leader election
- [x] In "Runtime Architecture", discuss local vs external messaging. Mention competing consumers
- [x] In "messages and serialization", discuss Memory/MessagePack alternatives
- [x] In "Message Handlers", make it clear there's no runtime Reflection
- [x] Check the header structure in "Error Handling" so more options are apparent. Make sure there's a sample of custom actions and sending messages back to original caller
- [x] In "Message Handlers", more discussion on the compound handler methods, what they mean, how they're ordered, discovered
- [ ] In "Message Handler Parameters", add a link or discussion on the new chain parameter attribute model coming soon
- [ ] In "Message Handlers", link to elements within the doc of what's possible. Show much more complex example
- [x] In "Message Handlers / Cascaded Messages" make sure it's clear that cascading is just publishing another message. Call out side effects. Contrast side effects to cascaded messages. Link to blog post
- [x] In "Middleware", make the point that middleware can be more selectively applied chain by chain
- [x] In "Fluent Validation" middleware, link to the HTTP version!!!
- [x] In "Getting Started with Wolverine as Message Bus", change note about multiple brokers of same type
- [x] In "Broadcast Messages to a Specific Topic", make it clear you need one topic sink endpoint!!!
- [ ] Flesh out Endpoint Policies
- [x] In "Http Services with Wolverine", hammer home that Wolverine.HTTP has great integration with messaging & the Marten event store. Full blown event driven architecture. Make the point that it's better for Vertical Slice Architecture than the more common MediatR + Minimal API combo
- [x] In "ASP.Net Core Integration" call out the new service registrations in 3.0
- [x] In Marten documentation, make sure to link to the HTTP usage as well
- [x] In the main "Durability" page, make it more generic about database integration. Bump inbox / outbox down a level. Mention that it's usable from HTTP endpoints, and non-HTTP / non message handlers
- [x] Break up the main durability page. Link to other databases, but don't include them here. Mention scheduled messaging. Node storage. Make sure folks know that message persistence is necessary for leadership election

For the runtime architecture, see this comment from Discord:

"
Is there any good, centralized documentation around how Wolverine operates in a multi-node cluster as part of a Critter Stack (assuming an IntegrateWithWolverine() call and minimal custom configuration)? I'm looking to understand how prioritization of "local handling versus remote handling", how competing consumers consume messages, how node failures are handled...basically the "workflow" between cascading messages being returned from a handler and being consumed by a handler somewhere within the multi-node configuration (assuming that durable inboxes and outboxes are being used - if that focuses the discussion at all). 

"
