### ISSUE TITLE
Inject tenant id into HTTP handlers or message handlers

### ISSUE THREAD

**Issue by DurinMusicspear** [JasperFx/wolverine#1097]
**Is your feature request related to a problem? Please describe.**
We work with non-Wolverine services and have to get/set tenant ID explicitly in many cases.

**Describe the solution you'd like**
It would be helpful if we could just inject `string tenantId` or have a special type `TenantId` that could be injected into HTTP and message handlers.

**Describe alternatives you've considered**
Getting tenantId from Envelope is fine for message handler, and using IQuerySession in HTTP handlers works. But its creates extra dependencies that we need to create or mock in the unit tests.

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] New TenantId record type
- [ ] Have TenantId returned / created by the tenant id detection frames just to make ordering work
- [ ] New variable source for it that picks it off of IMessageContext if it doesn't exist otherwise
- [ ] Test in message handler
- [ ] Test in http endpoint 
- [ ] Docs
