### ISSUE TITLE
Add support for Marten multi-tenancy to the Marten middleware

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#14]
Might require some work on the Marten side of things. I think I'd want an `ISessionFactory<T>` where the T could be Jasper's `IExecutionContext`

**Comment by wdkr** [comment]
When a scheduled message is handled for a specific tenant I'd like to inject an `IDocumentSession` for this tenant in my handler. Currently the injected session has the default TenantId. For example, the output of the program below is `envelope.TenantId: test, session.TenantId: *DEFAULT*`. Would that be resolved by this issue?

I can always use `session.ForTenant(envelope.TenantId)` in my handlers, but it's easy to forget. Is there a better workaround?

```C#
using Marten;
using Oakton;
using Wolverine;
using Wolverine.Attributes;
using Wolverine.Http;
using Wolverine.Marten;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddMarten(options =>
    {
        options.Connection(builder.Configuration.GetConnectionString("Marten")!);
    })
    .IntegrateWithWolverine()
    .ApplyAllDatabaseChangesOnStartup();

builder.Host.UseWolverine(options =>
    {
        options.Policies.AutoApplyTransactions();
        options.Policies.UseDurableLocalQueues();
    });

builder.Host.ApplyOaktonExtensions();

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(opts => opts.EnableTryItOutByDefault());
}

app.MapWolverineEndpoints();

return await app.RunOaktonCommands(args);

public sealed record Ping(string TenantId);
public sealed record Pong();

[WolverineHandler]
public static class PingPongEndpoints
{
    [WolverinePost("/ping")]
    public static async Task<IResult> Ping(Ping ping, IMessageBus bus)
    {
        bus.TenantId = ping.TenantId;
        await bus.ScheduleAsync(new Pong(), TimeSpan.FromSeconds(1));
        return Results.Ok();
    }

    public static void Handle(Pong _, Envelope envelope, IDocumentSession session)
    {
        Console.WriteLine($"envelope.TenantId: {envelope.TenantId}, session.TenantId: {((Marten.Internal.Sessions.QuerySession)session).TenantId}");
    }
}
```

**Comment by jeremydmiller** [comment]
@wdkr Sorry for the very, very slow response, but yes

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] IntegrateWithWolverine(), gets an option for `masterDatabase`
- [ ] Set up test harness that spins up Marten + Wolverine + `IntegrateWithWolverine()` with multiple databases
- [ ] `IntegrateWithMarten()` registrations create a `MultiTenantedMessageDatabase` object for the `IMessageStore`
- [ ] Override the master database
- [ ] Verify that only one database is the master and has the node persistence
- [ ] Test that every database gets the envelope tables
- [ ] Implement the database agent as agents family on `MultiTenantedMessageDatabase`
- [ ] Test that the database agents are spread out
- [ ] Prove that only the master database is using the control queue
- [ ] Has a stateful resource for every possible database + the master database
- [ ] Send messages that save documents by tenant. See that the changes are tenant specific.


## Chaos Testing

- [ ] Send a mix of messages by tenant, stop/start senders and receivers


## Tests on MultiTenantedMessageDatabase

In all cases, test w/ no tenant id and tenant id

- [ ] `LoadDeadLetterEnvelopeAsync`
- [ ] `DrainAsync()` -- might be a smoke test, but also gets covered by just shutting down the host
- [ ] `IMessageInbox.ScheduleExecutionAsync`
- [ ] `IMessageInbox.MoveToDeadLetterStorageAsync(Envelope envelope, Exception? exception)`
- [ ] `IncrementIncomingEnvelopeAttemptsAsync`
- [ ] `StoreIncomingAsync`
- [ ] `StoreIncomingAsync(IReadOnlyList<Envelope> envelopes)` -- this one you gotta do it all one way, then all mixed
- [ ] `IMessageInbox.ScheduleJobAsync(Envelope envelope)`
- [ ] `IMessageInbox.MarkIncomingEnvelopeAsHandledAsync(Envelope envelope)`
- [ ] `IMessageInbox.ReleaseIncomingAsync(int ownerId)`, might be a smoke test
- [ ] `IMessageInbox.ReleaseIncomingAsync(int ownerId, Uri receivedAt)` 
- [ ] `LoadOutgoingAsync(Uri destination)`
- [ ] `StoreOutgoingAsync(Envelope envelope, int ownerId)`
- [ ] `IMessageOutbox.DeleteOutgoingAsync(Envelope[] envelopes)` -- all one tenant, then mixed tenant
- [ ] `IMessageOutbox.DeleteOutgoingAsync(Envelope envelope)`
- [ ] `IMessageOutbox.DiscardAndReassignOutgoingAsync(Envelope[] discards, Envelope[] reassigned, int nodeId)` -- might take some time
- [ ] `IMessageStoreAdmin.ClearAllAsync()`
- [ ] `IMessageStoreAdmin.MarkDeadLetterEnvelopesAsReplayableAsync(string exceptionType)`
- [ ] `IMessageStoreAdmin.RebuildAsync()`
- [ ] `IMessageStoreAdmin.FetchCountsAsync()`
- [ ] `IMessageStoreAdmin.AllIncomingAsync()`
- [ ] `IMessageStoreAdmin.AllOutgoingAsync()`
- [ ] `IMessageStoreAdmin.ReleaseAllOwnershipAsync()`
- [ ] `IMessageStoreAdmin.CheckConnectivityAsync(CancellationToken token)` -- smoke test
- [ ] `IMessageStoreAdmin.MigrateAsync()` -- smoke test
