### ISSUE TITLE
Move GenerationRules to the root of WolverineOptions

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#176]
No longer makes sense where it's at

**Comment by jeremydmiller** [comment]
This was originally about moving the CodeGeneration down to WolverineOptions. I don't think it gets modified very often.

Today `NodeSettings` has:
* The unique node id & service name
* Lots of advanced options around durability
* ServiceName
* The code generation rules

## Tasks

- [ ] Create a new Serialization hive on WolverineOptions
- [ ] Rename NodeSettings to DurabilitySettings
- [ ] Move CodeGeneration props for adding variable source & type load mode to policies
- [ ] CodeGeneration should not be public 
- [ ] Keep `StubAllExternalTransports` on WolverineOptions
