### ISSUE TITLE
Azure Service Bus Support

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#21]

**Comment by jeremydmiller** [comment]
See https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk-2

**Comment by jeremydmiller** [comment]
## Notes

* Use a dedicated `ServiceBusClient` per endpoint
* Use `asb://queue/[name]` for queues
* Use `asb://topic/[name]` for just topics (sender)
* Use `asb://topic/[name]/[subscription name]` for listening to a specific subscription

## Tasks 

- [ ] Inline sender
- [ ] Batched sender for buffered or durable usage
- [ ] Inline listener
- [ ] Batched listener for buffered or durable usage
- [ ] Parallelized listener

### `AzureServiceBusQueue`
- [ ] Url pattern
- [ ] transport can find by endpoint
- [ ] Can create a queue using the management API
- [ ] Can purse using the management API ???
- [ ] Can create a sender for inline/buffered/durable
- [ ] Can create a listener for inline/buffered/durable

### `AzureServiceBusTopic`
- [ ] Url pattern
- [ ] transport can find by endpoint
- [ ] Can create a topic using the management API
- [ ] Can purse using the management API ???
- [ ] Can create a sender for inline/buffered/durable
- [ ] Can create a listener for inline/buffered/durable

### `AzureServiceBusSubscription`
- [ ] Url pattern
- [ ] transport can find by endpoint
- [ ] Can create a subscription using the management API
- [ ] Can purse using the management API ???
- [ ] Can create a sender for inline/buffered/durable
- [ ] Can create a listener for inline/buffered/durable

### Tests
- [ ] Compliance tests for buffered
- [ ] Compliance tests for inline
