### ISSUE TITLE
AWS SQS & SNS Support

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#22]
Not sure if that'll require a separate library or not yet. Hoping that LocalStack is viable

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] config the batch size for sending and receiving
- [ ] config the polling time
- [ ] does it support delayed delivery? That's cool.
- [ ] default credentials?
- [ ] configure the credentials. Chain in FI?
- [ ] alter the AmazonSQSConfig. Like Rabbit MQ?
- [ ] AutoProvision
- [ ] AutoPurge
- [ ] IStatefulResource support
- [ ] prefix!!!
- [ ] SNS topics
- [ ] conventional routing
- [ ] conventions for SQS endpoints
- [ ] configure the queues
- [ ] dedicated reply queue?
- [ ] UseSqs(Action<AmazonSQSConfig>).Credentials()
- [ ] UseSqsFromLocalstackIfDevelopment() -- be nice to have a DEV setting
- [ ] build client in transport
- [ ] extension methods for listening & subscribing
- [ ] TransportCompliance for durable
- [ ] TransportCompliance for buffered
- [ ] TODO hunt
- [ ] Eliminate nullable warnings
