### ISSUE TITLE
Advanced Tenant Id tracking

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#259]
Breaking off from https://github.com/JasperFx/wolverine/issues/258

## Possible Tasks

- [ ] *Some* way to propagate via policy from message body???
- [ ] *Some* way to propagate "X-tenant-id" from HTTP request???
- [x] Overwrite Envelope.TenantId from `DeliveryOptions` ???
- [ ] Dedicated `ITenantedMessage` interface for messages?
- [ ] Dedicated `[TenantId]` attribute?

**Comment by jeremydmiller** [comment]
I'm kicking this can to 1.1

**Comment by jeremydmiller** [comment]
Duplicate now with #415
