### ISSUE TITLE
Session Id aware endpoints with Azure Service Bus

### ISSUE THREAD

**Issue by nmowatt** [JasperFx/wolverine#264]
I have a queue which uses Sessions, so I need to be able to set SessionId on each message. I'm not sure how I can do this today.

 Error I get when I don't set it is:
 
` System.InvalidOperationException: The SessionId was not set on a message, and it cannot be sent to the entity. Entities that have session support enabled can only receive messages that have the SessionId set to a valid value.`

My workaround for now is to propagate messages using IProjection in Marten, where I do the following:

`var msg = new ServiceBusMessage(@event.Data.ToString()) {
          SessionId = @event.StreamId.ToString()
   };`

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Envelope.GroupId
- [ ] DeliveryOptions.GroupId
- [ ] DeliveryOptions.Override maps it
- [ ] Add mapping to `AzureServiceBusEnvelopeMapper`
- [ ] End to end w/ FIFO queue
- [ ] End to end w/ Azure SErvice Bus scheduled messages
- [ ] ISendMyself helper. `object.WithGroupId(string)` and object.WithSessionId(string) in Azure Service Bus model
