### ISSUE TITLE
Introduce a higher speed serializer option

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#32]
Do some research. Should do before 1.0 to verify the abstraction

**Comment by jeremydmiller** [comment]
Honestly, this is going to be a documentation effort only. Not shipping anything right now.

**Comment by jeremydmiller** [comment]
I want to try to use [MemoryPack](https://github.com/Cysharp/MemoryPack) here. Looks easy to use, perf numbers are off the charts. It'd need to be done in a separate extension Nuget to avoid taking the dependency.

## Tasks

- [ ] Implementation of a MemoryPack version of Wolverine's `IMessageSerializer`
- [ ] An extension method on `WolverineOptions` to register that serializer globally
- [ ] Extension methods to add that serializer to listeners and/or subscribers?
- [ ] Test it end to end where it has to go over the wire. Could be just over TCP

**Comment by jeremydmiller** [comment]
Done with the MemoryPack option!
