### ISSUE TITLE
DurabilityAgent Improvements

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#39]
Epic spanning the work to close #10, #16, #26, #29, and #30

**Comment by jeremydmiller** [comment]
## IDurableProcessor

```csharp
public interface IDurableProcessor
{
    int QueuedCount {get;} // for back pressure
    ListeningStatus Status {get;} // is it latched?
    void Enqueue(Envelope envelope);
}
```



## Tasks

- [ ] New incoming status constant for "Handled"
- [ ] New messaging action to delete old "Handled" envelopes
- [ ] Add a "mark deleted" action for incoming envelopes
- [ ] Add the Status=? filter checks everywhere that should be
- [ ] Account for Handled in the metrics
- [ ] Persisting an incoming envelope needs to be TryPersist() that can cleanly reject duplicate messages
- [ ] Cleanly discard incoming envelopes that are duplicates in durable receivers
- [ ] New `IDurableProcessor` interface. Implemented by `DurableLocalQueue` and `SendingAgent`
- [ ] RecoverIncomingEnvelopes, execute endpoint by endpoint. Take into account circuit breaker. Take into account queued count and maximum local messages to determine the maximum number of messages to accept
- [ ] New `IMessagingAction` to delete obsolete incoming messages. Scheduled on a timer.


### Postgresql
- [ ] Add a new column to incoming envelopes for "keep_until"
- [ ] Test try save envelope with duplicate message id

### Sql Server
- [ ] Add a new column to incoming envelopes for "keep_until"
- [ ] Test try save envelope with duplicate message id

**Comment by jeremydmiller** [comment]
I'm declaring victory. The remaining work doesn't feel super important
