### ISSUE TITLE
Multi-tenancy support for Wolverine.HTTP

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#415]
This is a placeholder. Today you would have to delegate to Wolverine message handling to get the full integration with the outbox and the transactional middleware.

**Comment by Xzelsius** [comment]
We could highly use this :)
How may we help to get this implemented?

**Comment by jeremydmiller** [comment]
@Xzelsius The single best thing would be to outline how you might be capturing the tenant id today and what your use cases are. JasperFx is open for business if you'd like to hire us to build that out, or hit the GitHub sponsorships:)

But let's start by just understanding more about your needs. I bailed on this for the runup to 1.0 mostly out of time and not having concrete feedback about how folks would use it.

**Comment by jeremydmiller** [comment]
@Xzelsius **Finally** on this a little bit this week. Wolverine is going to need a solution that doesn't require stuffing things into a scoped container type of trick.

**Comment by jeremydmiller** [comment]
Here we go, let's come with some strategies & honestly just some docs. To make this work with just Marten for right now, with EF Core multi-tenancy some time later, we need to:

1. Detect the tenant id from the HttpContext, some how, some way
2. Set MessageContext.TenantId = the detected tenant id

## Tasks

- [ ] `WolverineHttpOptions.TenantId.IsRouteArgumentNamed("foo")` -- creates a policy
- [ ] `[TenantId("route arg")]`, or make `[TenantId]` on a route parameter for one offs. Will need to throw if not a route argument
- [ ] `WolverineHttpOptions.TenantId.IsQueryStringValue("key") -- creates policy
- [ ] `WolverineHttpOptions.TenantId.IsRequestHeaderValue("key") -- creates policy
- [ ] `WolverineHttpOptions.TenantId.IsClaimNamed("key") -- creates policy
- [ ] New way to add custom middleware that's first inline
- [ ] Documentation on custom strategies

**Comment by Xzelsius** [comment]
I hope to find some time later today to test out the new features locally :)
