### ISSUE TITLE
Filter OpenTelemetry events

### ISSUE THREAD

**Issue by agross** [JasperFx/wolverine#451]
This is a screenshot of the Jaeger UI after starting the app with a previously empty Jaeger database.

![image](https://github.com/JasperFx/wolverine/assets/16245/eb169aab-57c5-4322-b5f0-80dcb22b3f68)

After a couple of minutes the outlier to the left contains around 150 spans related to background operations. I could get rid of them by filtering spans with the opentelemetry-collector:

```yaml
processors:
  filter/wolverine-internal:
    traces:
      span:
        - 'IsMatch(attributes["messaging.message_type"], "^Wolverine\\.RDBMS\\..*")'
        - 'IsMatch(attributes["messaging.message_type"], "^Wolverine\\.Runtime\\.Agents\\..*")'
        - 'IsMatch(attributes["db.statement"], "wolverine_messages")' # These are Npgsql statements issued by the background job.
```

Perhaps it's not necessary to log those spans in the first place.

**Comment by jeremydmiller** [comment]
@agross I'm going to have to push this one off until maybe next week. Or at least it's not going in 1.1.3 today.

**Comment by jeremydmiller** [comment]
And I'm pushing this off yet again since there is a workaround.

**Comment by jeremydmiller** [comment]
## Notes

* This PR has a solid start to filtering: https://github.com/JasperFx/wolverine/pull/541
* Might be more mechanically suitable to do the filtering at the endpoint level rather than by message type
* Latch at endpoint for sending/receiving. Can latch at message type for sending too.
* Could latch activity tracing in HandlerPipeline. That handles execution
* Latch in Receiver too
* Use different IExecutor or IExecutor decorators for message type filtering on execution. Remove the tracing from InvokeInlineAsync? -- *Nah, just use a boolean flag*
* Consider latching the audit logging on internal messages too

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Configure telemetry enabled by endpoint
- [ ] Enable/disable telemetry on all listener types
- [ ] Enable/disable telemetry on all sending agent types
- [ ] Disable telemetry on database control queues
- [ ] Disable telemetry on all agent queues and internal actions
