### ISSUE TITLE
Improve the diagnostics on pre-built type generation and finding

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#539]
## Tasks

- [ ] If mode is dynamic, log note about the potential performance and link to the docs page
- [ ] If mode is auto, log note about the application assembly
- [ ] If mode is static, log the application assembly and link to the docs page
- [ ] Update documentation with debugging instructions, including the environment check
- [ ] Make sure there's good ToString() implementations on all Wolverine ICodeFile types for better error messages
