### ISSUE TITLE
Endpoint Configuration Policies

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#6]
Need the ability to specify properties of various endpoints more easily

## Tasks

- [x] Rabbit MQ conventional routing needs an allow/deny list filter. Chain configuration for listener/sender using expression somehow
- [x] Policies.UseDurableInboxForAllListeners()
- [x] Policies.UseDurableOutboxForAllSenders()
- [x] chain configuration for Rabbit MQ listeners
- [x] chain configuration for Rabbit MQ senders
- [x] Policies.LocalQueues(configure)
- [ ] Policies.UseSeparateLocalQueueForEachMessageType(configure)
- [x] New way of registering endpoint policies
