### ISSUE TITLE
1.10 Documentation Punchlist

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#617]
## Tasks

- [x] Optimizing for Serverless in tutorials
- [x] Add context about disabling the durability in "Wolverine as Mediator" section
- [x] Troubleshooting the inbox / outbox
- [x] Talk about Solo mode in the root inbox page, again on troubleshooting
- [x] Call out the durability agent enabled

**Comment by jeremydmiller** [comment]
Declaring victory
