### ISSUE TITLE
New Open API Generation

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#665]
The existing OpenAPI generation in AspNetCore is literally hard-coded for MVC Core. We'll need to have our own strategy.

## Tasks

- [x] New implementation of `IApiDescriptionProvider` registered in IoC
- [x] Do not put the MethodInfo for an HttpChain into metadata
- [x] Request body
- [x] Response body when exists is the Wolverine `ResourceType`
- [x] Test route arguments that appear in the main method
- [x] Test route arguments that are only used by middleware
- [x] Test parameter arguments that are query strings
- [x] Test parameter arguments that are declared from headers
- [x] HttpChain should track query string variables like it does with routes. That will enable the parameter descriptions
