### ISSUE TITLE
Feat: Configure PostgreSQL durable messages with NpgsqlDataSourceBuilder

### ISSUE THREAD

**Issue by codyspeck** [JasperFx/wolverine#691]
**Is your feature request related to a problem? Please describe.**
At the moment, Wolverine only supports using a static connection string when configuring the PostgreSQL durable persistence store implemented [here](https://github.com/JasperFx/wolverine/blob/main/src/Persistence/Wolverine.Postgresql/PostgresqlConfigurationExtensions.cs). This is problematic when trying to use rotating credentials / dynamic passwords to connect to a PostgreSQL database. In my particular case, I'm using [IAM database authentication](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.IAMDBAuth.html) which rotates access tokens every 15 minutes.

**Describe the solution you'd like**
I would like an [NpgsqlDataSourceBuilder](https://www.npgsql.org/doc/security.html) to be able to be supplied in place of a static connection string. This seems to [already be an option](https://github.com/JasperFx/marten/blob/6a66ab4765fbfad9d1b8daa45e036650226c6efd/src/Marten/StoreOptions.cs#L290) when configuring Marten.

**Describe alternatives you've considered**
My current plan to circumvent this issue is to manually manage [PostgreSQL's password file](https://www.postgresql.org/docs/current/libpq-pgpass.html) in application code on credential rotation. This involves overwriting a file on disk and manually flushing out existing connection pools such that new connections re-query the password file. This could work, but I find it a much less attractive option.

**Additional context**
-

**Comment by jeremydmiller** [comment]
@codyspeck Thought about this a little bit while walking the dog. I *think* it might require Wolverine 2.0 to introduce some kind of `IConnectionFactory` abstraction like we have in Marten, but on the DatabaseSettings within Wolverine. That being said, go for it if you're up for that.

I'm not thinking that the `NpgsqlDataSource` would help here, but I'm happy to be wrong about that. From initial experiments with Marten, that's not exactly a drop in thing at all.

And I'd be very happy for some help, thank you!

**Comment by jeremydmiller** [comment]
## Notes

I'm hijacking this issue to deal with a couple different issues:

1. Eliminate the need for "Persist Security Info" in connection strings with Wolverine 2.0 because of the Npgsql changes
2. Utilize NpgsqlDataSource and SqlDataSource as much as possible
3. Allow for configuring directly with the data source
4. Utilize Aspire configuration for both NpgsqlDataSource and SqlDataSource

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Add DbDataSource prop to `DatabaseSettings`
- [ ] PostgresqlMessageStore needs to use ctor with NpgsqlDataSource signature
- [ ] In `MartenMessageDatabaseSource.createWolverineStore`, cast to `PostgresqlDatabase`, grab data source
- [ ] `WolverineOptionsMartenExtensions.IntegrateWithWolverine()` should try to pull all database sources from Marten
- [ ] Check for Marten `ITenancyWithMasterDatabase`
- [ ] New options for PersistWithPostgresql() that takes in an NpgsqlDataSource
- [ ] New option for IntegrateWithWolverine that takes in an NpgsqlDataSource
- [ ] Try for loading the data store from IoC?
