### ISSUE TITLE
"Sticky" Listeners that only run on one Node

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#784]
What if Wolverine had the ability to make the message listener for an endpoint (a Rabbit queue, an Azure Service Bus queue, a Kafka topic) **only** active on a single node within a Wolverine cluster? This potentially gives Wolverine the ability for:

1. Strictly ordered message handling at a single endpoint. You can't get that with competing consumers.
2. A form of [virtual actors](https://www.microsoft.com/en-us/research/project/orleans-virtual-actors/) for Wolverine. Not sure how aggressively we'd build on top of that, but it's possible

**Comment by lcorneliussen** [comment]
One active box per queue could be a start, but wouldn’t wolverine need to route to a certain box based on the actor id? (either via a partitioning scheme, or via a persisted registry of which key is running where?)

**Comment by jeremydmiller** [comment]
@lcorneliussen Cruder than that. If wolverine is publishing to an endpoint where only the one sticky listener is handling it, you're de facto a poor man's actor.

**Comment by jeremydmiller** [comment]
Oh, and Wolverine does have the ability to let you define your own distribution of "sticky" agents across a cluster of nodes. Not documented right now, but used under the covers for some of the inbox/outbox stuff and the "Critter Stack Pro" commercial tooling that distributes asynchronous projections over a cluster

**Comment by jeremydmiller** [comment]
## Tasks

- [ ] Endpoint.ListenerScope default is CompetingConsumers
- [ ] `ListenerConfiguration.StrongOrderedGuarantees()`, sets all the necessary defaults
- [ ] Do not automatically start up a listening endpoint with ListenerScope = Exclusive
- [ ] New `ListenerAgentFamily` implementation
- [ ] Test end to end?
