### ISSUE TITLE
Support Azure Service Bus topics

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/wolverine#87]
Honestly skipping this for the moment because of the extra cost:-)

**Comment by mumby0168** [comment]
> Honestly skipping this for the moment because of the extra cost:-)

Is this as in the cost of needing to provision a Standard SKU service bus instance?

Do any of the other providers support a similar model to topics and subs already?

**Comment by jeremydmiller** [comment]
I just need to pursue this and the AWS equivalent programs: https://cloudblogs.microsoft.com/opensource/2021/09/28/announcing-azure-credits-for-open-source-projects/

The Rabbit MQ transport is full featured already with support for both topics and rabbit mq bindings as well as simple publishing to queues.

**Comment by jeremydmiller** [comment]
## Tasks

Don't for a second assume that this list is complete, I'm just jotting down some notes in case someone wants to take this on sooner rather than waiting for me to get around to it.

- [ ] Get into `AzureServiceBusTopic`, implement the methods that implement `NotImplementedException`. Most of the methods are for checking whether the topic actually exists in Azure Service Bus, deleting the topic, or building it. See `AzureServiceBusQueue` to kind of see the pattern
- [ ] `AzureServiceBusTopic.CreateSender()` should end up being the same code as `AzureServiceBusQueue`
- [ ] New fluent interface helpers to `PublishMessage<T>().ToAzureServiceBusTopic(topic name)`. See the Rabbit MQ or Azure Service Bus equivalents to queues or topics
- [ ] End to end tests, duh. 
- [ ] Probably need to add an `AzureServiceBusSubscription` model similar to the Rabbit MQ binding model in the rabbit transport. Just to enable Wolverine to build the subscriptions on demand
- [ ] *Optionally* -- may want to make an opt in message routing convention for Azure Service Bus topics
